### PR TITLE
Bug fix: links and images being removed after save

### LINKED ISSUE #445: Fix article editor to persist hyperlinks on save

### PR DESCRIPTION
**Pull request by psiemens**
Close #445

### CODE REVIEW

File: dispatch/static/manager/src/js/components/ContentEditor/ContentStateHelper.js [hunk 1]
```diff
@@ -46,12 +30,71 @@ function parseBlock(block) {
...
+  return {
+    contentBlocks: [contentBlock],
+    entityMap: {entityKey: entity}
+  }
+
+}
+
+function createBlock(acc, block) {
+
+  var blocksFromJSON
```
Comment (JimFung) [inline dispatch/static/manager/src/js/components/ContentEditor/ContentStateHelper.js]: should be a let
